### ISSUE TITLE
Compilation FYIs

### ISSUE THREAD

**Issue by MartyWallace** [shannonarcher/astar-ts#1]
TypeScript 1.5 introduced the [`tsconfig.json`](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) which you might prefer over using Grunt. Though, you will still need a task to minify your code as TypeScript doesn't support minified output.

[For minification you might like Gulp better anyway](https://www.npmjs.com/package/gulp-uglify). Writing gulp tasks is way nicer and their piping system makes a lot more sense vs having to make shitty temp files with Grunt:

    var gulp = require('gulp');
    var uglify = require('gulp-uglify');
     
    gulp.task('compress', function() {
        return gulp.src('lib/*.js')
            .pipe(uglify())
            .pipe(gulp.dest('build'));
    });

Gulp even has file watching inbuilt already, so you just need:

    gulp.task('watch', function() {
        gulp.watch('lib/*.js', ['compress']);
    });

For that :+1:

**Comment by shannonarcher** [comment]
Thanks for the great advice.
