### ISSUE TITLE
How to define a wall?

### ISSUE THREAD

**Issue by wilhantian** [shannonarcher/astar-ts#3]
[
  [0, 0, 0, 0, 0],
  [0, 5, 5, 5, 0],
  [0, 5, 5, 5, 0],
  [0, 5, 5, 5, 0],
  [0, 0, 0, 0, 0],
]

0 = wall? or 5 = wall?

**Comment by martywallace** [comment]
@wilhantian I don't believe there is a concept of "Walls", the values represent a weighting to be added to the cost of the path.

**Comment by wilhantian** [comment]
@MartyWallace Thanks~

**Comment by shannonarcher** [comment]
A wall can be simulated by a high cost value being assigned to a node. Once a path is found you can then check if any of the nodes on the path have a cost equal to this high cost value and then treat it as not having found a path.
